name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Cài đặt dependencies frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    # Chạy test frontend
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false

    # Build frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # Cài đặt dependencies backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    # Chạy test backend
    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    # Build backend (nếu có bước build, ví dụ dùng babel)
    # - name: Build backend
    #   working-directory: ./backend
    #   run: npm run build

    # (Tuỳ chọn) Upload test coverage, báo cáo, hoặc deploy

